package:
  name: opensees
  version: 0.0.20

source:
  path: ../..

build:
  script_env: [CONDA_PREFIX]
  script: "{{PYTHON}} setup.py install -v -- -- -j8"

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - cmake
    - build
    - scikit-build
    - setuptools

  host:
    # Conda-Forge
    - tk
    - mysql
    - libblas
    - liblapack
    - arpack
    - python
    - scikit-build
    - pybind11
    - pip !=22.1.0

  run:
    - python
    - numpy
    - matplotlib


  test:
    requires:
      - pytest
      - nbmake
    imports:
      - opensees
    source_files:
      - notebooks/
    commands:
      - python -m pytest --nbmake notebooks/


about:
  summary: "Idiomatic and idempotent bindings to the OpenSees framework."
  license: UNKNOWN
  license_family: OTHER
  doc_url: https://brace2.github.io/OpenSeesRT
  dev_url: https://github.com/BRACE2/OpenSeesRT

extra:
  recipe-maintainers:
    - claudioperez

