#!/bin/bash
#second parameter is prefix to be added in pdftex file to point to correct figure path. Include forward slash!

path=${1%/*};
path=${path##*/};
escapedpath=`echo $path | sed 's/\//\\\\\//g'`;
basename="`echo ${1##*/} | sed 's/\.pstex_t//'`";
basepath=${PWD#$HOME/};
escapedbasepath=`echo $basepath | sed 's/\//\\\\\//g'`;

cd $path;

echo "\documentclass{article}
\usepackage{epsfig}
\usepackage{graphicx}
\usepackage{color}
\pagestyle{empty}
\begin{document}
\input{ $basename.pstex_t }
\end{document}" > driver.tex;

if latex -interaction="nonstopmode" driver.tex; then
	dvips -E driver.dvi -o $basename-standalone.eps;
	echo "File written: $basename-standalone.eps";
	epstopdf $basename-standalone.eps;
	echo "File written: $basename-standalone.pdf";
fi


epstopdf --outfile $basename.pdf $basename.pstex;
echo "File written: $basename.pdf";

#echo "\documentclass{article}
#\usepackage{epsfig}
#\usepackage{graphicx}
#\usepackage{color}
#\pagestyle{empty}
#\begin{document}" > driver.tex;
#cat $basename.pstex_t | sed 's/\.pstex/\.pdf/' >> driver.tex;
#echo "\end{document}" >> driver.tex;
#
#if pdflatex -interaction="nonstopmode" driver.tex; then
#	mv driver.pdf $basename.pdf;
#fi

cat $basename.pstex_t | sed "s/includegraphics{/includegraphics{$2$escapedpath\//" | sed 's/\.pstex/\.pdf/' > $basename.pdftex_l;
echo "File written: $basename.pdftex_l";
cat $basename.pstex_t | sed "s/includegraphics{/includegraphics{$2$escapedpath\//" > $basename.pstex_l;
echo "File written: $basename.pstex_l";

rm -f driver.tex;
rm -f driver.log;
rm -f driver.dvi;
rm -f driver.aux;
