#!/usr/bin/env python

# Claudio Perez

import sys

TEST_LEVELS = {
}

def parse_args(args):
  opts = {
    "component_type": None
  }
  argiter = iter(args)
  for arg in argiter:
    if arg == "--help":
      print("""
      """)
      sys.exit()
    else:
      opts["component_type"] = arg
  return opts

if __name__=="__main__":
    opts = parse_args(sys.argv)
