#!/bin/bash

cat - <<EOF
import opensees
from opensees import section, patch, layer, analysis, pattern
EOF

cat $1 | {
  # NO MORE WIPE!
  perl -pe 's/wipeAnalysis\(/# \&/g'
} | {
  perl -pe 's/wipe\(/# &/g'
} | {
  # MODELING
  perl -pe 's/model\(["'"'"'A-z]*, ["'"'"']-ndm["'"'"'], *([0-9]), *["'"'"']-ndf["'"'"'], *([0-9])\)/m = opensees.model(ndm=$1, ndf=$2)/g'
} | {
  perl -pe 's/node\(/m.node(/g'
} | {
  perl -pe 's/fix\(/m.fix(/g'
} | {
  perl -pe 's/[A-z\.]*element\(["'"'"']([A-z0-9]*)["'"'"'],/element.$1(/g'
} | {
  perl -pe 's/truss/Truss/g'
} | {
  perl -pe 's/[A-z\.]*uniaxialMaterial\(["'"'"']([A-z0-9]*)["'"'"'],/uniaxial.$1(/g'
} | {

  # PATTERNS
  perl -pe 's/timeSeries\("Linear", 1\)/# &/g'
} | {

  # ANALYSIS
  perl -pe 's/system\(([A-z0-9-., "'"'"']*)\)/strategy = dict(\n  system = ($1,),/g'
} | {
  perl -pe 's/algorithm\(([A-z0-9-., "'"'"']*)\)/  algorithm = ($1,),/g'
} | {
  perl -pe 's/numberer\(([A-z0-9-., "'"'"']*)\)/  numberer = ($1,),/g'
} | {
  perl -pe 's/constraints\(([A-z0-9-., "'"'"']*)\)/  constraints = ($1,),/g'
} | {
  perl -pe 's/integrator\(([A-z0-9-., "'"'"']*)\)/  integrator = ($1,),\n)/g'
}

